language: java
dist: trusty
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "jabbarra"

cache:
  directories:
  - $HOME/.m2
script:
  - ./mvnw install sonar:sonar
before_install:
  - chmod +x mvnw
  - echo $JAVA_HOME
after_success:
  - bash <(curl -s https://codecov.io/bash)
